spring:
    application:
        name: jobflow-backend
    profiles:
        active: local

jpa:
    hibernate:
        ddl-auto: validate
    properties:
        hibernate:
            format_sql: true
    show-sql: false
    open-in-view: false

flyway:
    enabled: false

server:
    port: 8081

jobflow:
    cors:
        allowed-origins: http://localhost:3000